### ISSUE TITLE
Unwanted scrollbars in split bar charts?

### ISSUE THREAD

**Issue by tkb** [datawrapper/datawrapper#185] opened 2016-01-20 17:39 UTC
Loving the new split bar charts but am intermittently finding both in datawrapper and when embedding them, that I see scrollbars on the right e.g.:

https://datawrapper.dwcdn.net/qsUsR/3/

In datawrapper, regardless of the height I set end up seeing them eventually:

![image](https://cloud.githubusercontent.com/assets/192869/12457455/89be69b2-bf72-11e5-8479-bd82164fe50c.png)

And they persist when the chart is embedded too, even setting the height to something huge (would normally use:

![image](https://cloud.githubusercontent.com/assets/192869/12457493/c615ca22-bf72-11e5-895d-d044a0863f63.png)

Thanks!

**Comment by davidkokkelink** [comment] 2016-01-20 18:06
indeed, thanks for reporting! the issue is fixed now. you'll need to re-publish the chart once, and then the scrollbars will be gone!

**Closed by davidkokkelink** 2016-01-20 18:06 UTC

**Comment by tkb** [comment] 2016-01-20 18:44
OK, thanks!
